{ lib, ... }:
{
  imports = [
    #./boot.nix
    #./disks.nix
    #./network.nix
    #./monitors.nix
    #../common/firmware.nix
    #../common/x86_64.nix
    #../common/cpu-amd.nix
    #../common/gpu-amd.nix
    #../../software/common/default.nix
    #../../software/desktop/default.nix
    ../../software/common/ssh.nix
  ];

  programs.zsh.enable = true;

  system.stateVersion = "25.11";

  # Begin autogenerated config

  # Use the extlinux boot loader. (NixOS wants to enable GRUB by default)
  boot.loader.grub.enable = false;
  # Enables the generation of /boot/extlinux/extlinux.conf
  boot.loader.generic-extlinux-compatible.enable = true;

  networking.hostName = "theia"; # Define your hostname.

  # Configure network connections interactively with nmcli or nmtui.
  networking.networkmanager.enable = true;

  # Begin autogenerated hardware config
  boot.initrd.availableKernelModules = [ "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
