{
  imports = [
    ./audio.nix
    ./boot-loader.nix
    ./desktop.nix
    ./fonts.nix
    ./gaming.nix
    ./gpg.nix
    ./graphical-session.nix
    ./garbage-collection.nix
    ./kernel.nix
    ./locale.nix
    ./network.nix
    ./packages.nix
    ./shell.nix
    ./user.nix
    ./wine.nix
  ];
}
